name: web_client
description: Web client for frontend.
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+21
  http: ^0.12.0+2

  core_module:
    path: ../.arrow/modules/core_module
  dnd_module:
    path: ../.arrow/modules/dnd_module

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.7.2
  build_test: ^0.10.2
  build_web_compilers: ^2.6.1
  sass_builder: ^2.1.2
  test: ^1.0.0
